# https://neptune.ai

neptune:
  _target_: lightning.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: ${oc.env:NEPTUNE_PROJECT_NAME}
  log_model_checkpoints: False
  name: ${name}
